### ISSUE TITLE
Incompatible with spree_auth_devise

### ISSUE THREAD

**Issue by lethjakman** [AlchemyCMS/alchemy_spree#15]
Hello,

I'm attempting to use your alchemy_spree plugin with spree commerce version 2.3.2. There seems to be a incompatibility between alchemy-devise and spree_auth_devise. Alchemy-devise depends on devise "~> 3.0.0", and alchemy_spree depends on '~> 3.2.3', I can get bundler working correctly if I remove spree_auth_devise, but then I lose my /login route, and thus the login capability for my customers. Is there an easy way to get the two working together that I'm not seeing? 

Thank you for your time!

**Comment by tvdeyen** [comment]
Will be fixed with with #20

**Comment by tvdeyen** [comment]
Update: Will be fixed with #21

**Comment by tvdeyen** [comment]
Thanks to @lethjakman and @tomg65 for providing your code. I made a branch that should fix this hard coded alchemy-devise dependency. 

Could you please test the allow-spree-user branch and report if this fixes your issues?

Thanks.

**Comment by tomg65** [comment]
I put the allow-spree-user branch in a copy of my existing application. (Custom user authentication with devise and rolify -> model = User )
It works good - I found no issues until now. Spree administration works in alchemy backend
I had to implement an additional method to the user model:
```
  def admin?
    if has_role? :admin
      true
    else
      false
    end
  end
```
Best
Thomas

**Comment by tvdeyen** [comment]
Thanks @tomg65

The method is an implementation error and will be fixed. 

Thanks for trying out.
