### ISSUE TITLE
undefined local variable or method 'cache_key_for_taxons'

### ISSUE THREAD

**Issue by renshah** [AlchemyCMS/alchemy_spree#22]
I have installed below gems.

em 'spree', github: 'spree/spree', branch: '2-4-stable'
gem 'spree_auth_devise', github: 'spree/spree_auth_devise', branch: '2-4-stable'
gem 'spree_gateway', github: 'spree/spree_gateway', branch: '2-4-stable'

gem 'alchemy_spree', github: 'magiclabs/alchemy_spree', branch: 'master'

And whenever try to run cms page, i am getting error 

undefined local variable or method `cache_key_for_taxons

How to fix it? 
![error](https://cloud.githubusercontent.com/assets/8312926/6930777/51e657d8-d7d4-11e4-8b48-a430ca73a057.png)

**Comment by mamhoff** [comment]
Is this still an issue? If so, reopen the issue.
