### ISSUE TITLE
Not able install alchemy_spree in spree 3.0 

### ISSUE THREAD

**Issue by joshuawatson** [AlchemyCMS/alchemy_spree#23]
I used rails 4.2 and ruby 2.2.1
Gemfile:-
gem 'alchemy_spree', github: 'magiclabs/alchemy_spree', branch: 'master'
gem 'spree', '3.0.0'
gem 'spree_gateway', github: 'spree/spree_gateway', branch: '3-0-stable'
gem 'spree_auth_devise', github: 'spree/spree_auth_devise', branch: '3-0-stable'

Error:-
Bundler could not find compatible versions for gem "spree":
  In snapshot (Gemfile.lock):
    spree (3.0.0)

  In Gemfile:
    alchemy_spree (>= 0) ruby depends on
      spree (< 3.0, >= 2.3) ruby

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

**Comment by tvdeyen** [comment]
Please use the `spree-3.0` branch. Thanks
