### ISSUE TITLE
undefined method `alchemy_roles'

### ISSUE THREAD

**Issue by Genkilabs** [AlchemyCMS/alchemy_spree#26]
It looks like alchemy expects users to have alchemy_roles and spree expects users to have spree_roles.
This is a bare bones Rails 4 app with both Spree and Alchemy installed. Spree is mounted to the '/store' path. This error can be thrown on any cancan role request, ie. can? or authorize!
The error seems to happen more after making code changes, then refreshing (while logged-in).

any ideas?

<img width="1244" alt="screenshot 2015-07-10 11 02 24" src="https://cloud.githubusercontent.com/assets/24028/8624227/a3128abe-26f3-11e5-8c9e-3ff86b710203.png">

**Comment by mamhoff** [comment]
Can you post your Gemfile and Gemfile.lock, please?

**Comment by mamhoff** [comment]
This appears to be stale. Closing.
