### ISSUE TITLE
Alchemy 4 support

### ISSUE THREAD

**Issue by k4roshi** [AlchemyCMS/alchemy_spree#30]
Is Alchemy 4 support planned?

**Comment by amitbishtZT** [comment]
Is the support planned ??

**Comment by tvdeyen** [comment]
I don't use Spree anymore. So, if someone plans support, please provide a PR and/or take over maintenance of this gem.

Even better: If possible for you switch to [Solidus](https://github.com/solidusio/solidus) (the successor of Spree) and it's Alchemy integration [`alchemy-solidus`](https://github.com/AlchemyCMS/alchemy-solidus).
